#!/usr/bin/env node
/**
 * Demo harness for stories with no browser surface.
 *
 * The counterpart to demo.ts. Same contract, different medium: a demo doc is a
 * generated artifact that exists only if the thing it documents actually ran, so
 * it cannot drift away from the code. Where the Playwright harness captures
 * screenshots of a user flow, this captures the output of the commands that
 * prove a CLI, library, migration or job works.
 *
 * Usage:
 *   node e2e/demo-command.mjs US-A01 "Provision the database" \
 *     --step "Apply the baseline schema" "npm run db:push" \
 *     --step "Confirm the tables exist" "psql -c '\\dt'"
 *
 * Exits non-zero if any step fails, and — like demo.ts — does NOT overwrite the
 * existing demo doc in that case, so a failed run cannot install itself as the
 * baseline that pr-review compares the next run against.
 */
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const [storyId, title, ...rest] = process.argv.slice(2);
if (!storyId || !title) {
  console.error('usage: demo-command.mjs <STORY-ID> <title> --step <caption> <command> [--step ...]');
  process.exit(2);
}

const steps = [];
for (let i = 0; i < rest.length; i++) {
  if (rest[i] === '--step') {
    steps.push({ caption: rest[i + 1], command: rest[i + 2] });
    i += 2;
  }
}
if (!steps.length) {
  console.error('At least one --step is required: a demo with no steps proves nothing.');
  process.exit(2);
}

const MAX_LINES = 40;

const results = [];
let failed = false;

for (const { caption, command } of steps) {
  process.stdout.write(`\n$ ${command}\n`);
  let output;
  let ok = true;
  try {
    output = execSync(command, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 600_000 });
  } catch (e) {
    ok = false;
    failed = true;
    output = `${e.stdout ?? ''}${e.stderr ?? ''}` || e.message;
  }
  process.stdout.write(output);
  results.push({ caption, command, output, ok });
  if (!ok) break; // a failed step makes everything after it noise
}

if (failed) {
  const bad = results.find((r) => !r.ok);
  console.error(`\n${storyId}: step "${bad.caption}" failed. Keeping the previous demo doc as the baseline.`);
  process.exit(1);
}

// Trim the middle rather than the end: the tail of command output is usually
// where the result is, and a doc that silently drops it is worse than a long one.
const trim = (s) => {
  const lines = s.replace(/\s+$/, '').split('\n');
  if (lines.length <= MAX_LINES) return lines.join('\n');
  const head = lines.slice(0, MAX_LINES / 2);
  const tail = lines.slice(-MAX_LINES / 2);
  return [...head, `… ${lines.length - MAX_LINES} lines omitted …`, ...tail].join('\n');
};

const body = [
  `# ${storyId} — ${title}`,
  '',
  `_Generated by this story's proving commands · ${new Date().toISOString().slice(0, 10)} · PASS_`,
  '',
  ...results.flatMap(({ caption, command, output }, i) => [
    `## ${i + 1}. ${caption}`,
    '',
    '```console',
    `$ ${command}`,
    trim(output),
    '```',
    '',
  ]),
].join('\n');

fs.mkdirSync('docs/demos', { recursive: true });
fs.writeFileSync(path.join('docs/demos', `${storyId}.md`), body);
console.log(`\nWrote docs/demos/${storyId}.md`);
